# Generated by Django 3.2.13 on 2022-10-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
