# Generated by Django 3.2.13 on 2022-10-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0002_auto_20221006_0908'),
        ('foodservice', '0003_auto_20221006_1200'),
    ]

    operations = [
    ]
