# Generated by Django 3.2.13 on 2022-10-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0005_auto_20221006_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'ингредиенты рецепта', 'verbose_name_plural': 'ингредиенты рецепта'},
        ),
    ]
