# Generated by Django 3.2.13 on 2022-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0006_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=3000, verbose_name='описание'),
        ),
    ]
