# Generated by Django 4.1.2 on 2022-10-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0010_alter_recipe_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
