# Generated by Django 3.2.13 on 2022-10-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип меню',
                'verbose_name_plural': 'тип меню',
            },
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient_measure',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_recipes', to='foodservice.menutype', verbose_name='тип меню'),
        ),
    ]
