# Generated by Django 4.1.2 on 2022-10-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0014_subscription_breakfast_subscription_desert_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionType',
        ),
    ]
