# Generated by Django 3.2.15 on 2022-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0015_delete_subscription_delete_subscriptiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes_with_allergen', to='foodservice.Allergen', verbose_name='Алергены'),
        ),
    ]
