# Generated by Django 3.2.15 on 2022-10-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0016_alter_recipe_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='recipes_with_allergen', to='foodservice.Allergen', verbose_name='Алергены'),
        ),
    ]
