# Generated by Django 4.1.2 on 2022-10-09 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0015_delete_subscription_delete_subscriptiontype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('term', models.IntegerField(verbose_name='Срок подписки')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'тип подписки',
                'verbose_name_plural': 'типы подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.AddField(
            model_name='subscription',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='foodservice.allergen', verbose_name='Алергены'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscritions', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='desert',
            field=models.BooleanField(default=True, verbose_name='Десерт'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dinner',
            field=models.BooleanField(default=True, verbose_name='Обед'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dishes',
            field=models.IntegerField(default=0, verbose_name='Количество блюд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='supper',
            field=models.BooleanField(default=True, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscritions', to='subscription.subscriptiontype', verbose_name='Клиент'),
        ),
    ]
