# Generated by Django 4.1.2 on 2022-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptiontype_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid_till',
            field=models.TimeField(blank=True, null=True, verbose_name='Оплачено до'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
