# Generated by Django 3.2.15 on 2022-10-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscription_type'),
        ('subscription', '0006_subscription_menu_type_alter_subscription_type'),
    ]

    operations = [
    ]
